name: build & test

on:
  push

jobs:
  build:

    runs-on: windows-latest
    steps:
        - uses: actions/checkout@v4

        - name: get game version
          run: >-
            Get-ChildItem -Force

