name: release game

on:
  release:
    types: [ created ]
jobs:
    
  build:
    runs-on: windows-latest
    steps:
        - uses: actions/checkout@v4

        - name: build game version
          run: >-
            ./psdk --util=project_compilation

        - name: publish game
          uses: actions/upload-artifact@v4
          with:
            name: release
            path: |
                Release
