name: deploy-prod

on:
  release:
    types: [ created ]
jobs:
    
  build:
    runs-on: windows-latest
    steps:
        - uses: actions/checkout@v4

        - name: Update version
          run: >-
            cmd.exe /k "psdk --util=project_compilation"

        - name: Archive production artifacts
          uses: actions/upload-artifact@v4
          with:
            name: dist-without-markdown
            path: |
                Release
